version: '3'

services:

  app:
    hostname: app
    build: './src/app'
    volumes:
      - './src/app:/usr/share/nginx/html'
    ports:
      - '8080:80'

  docker-push:
    image: 'tmvdl/projects:trader'
    build: './src/app'

  github-release:
    image: 'github-release'
    build: './src'
